### ISSUE TITLE
GSoC - Extend Casbin to the Frontend (Zihui Liu)

### ISSUE THREAD

**Issue by hsluoyz** [casbin/SummerOfCode2020#11]
GSoC Project: https://summerofcode.withgoogle.com/projects/#5147569409228800

![image](https://user-images.githubusercontent.com/3787410/83536228-87dcf800-a525-11ea-8ef9-6cd91652c4f1.png)

Student: @kingiw

Mentors: @hsluoyz @BetaCat0 @nodece 

IM Channel: Wechat group:

![image](https://user-images.githubusercontent.com/3787410/83617263-662e5000-a5bb-11ea-9f2c-278f817258e4.png)

Weekly reports will be appended as replies by the student.

**Comment by kingiw** [comment]
# Week 1 (June 2 - June 7)

## Job Summarization
1. Studied the fundamental knowledge about Typescript (Actually I am moving from JS to TS, so I am not very familiar with everything in TS).
2. Still setting up the environment (including the CI for service test). 
3. Conducted further investigation on other authorization library.

## Before Coding
Before get started, I think we should first clarify the differences between *node-casbin* and *casbin.js*. Only after we reach a consesus can I go further.

IMO, *node-casbin* is an implementation of all the functionalities of Casbin in JS/TS, which provides the functions like policy enforcement and role management. 

On the other hand, *casbin.js* should be an frontend JS library, serving as an agent to obtain and manage the authorities from a *Casbin kernel*. Here, *Casbin kernel* refers to a web service that runs on a backend server. Specifically, the core of *casbin.js* is mainly responsible for the following functionalities:
1. Sync the authorities with the Casbin kernel. (Probably by cookies)
2. Cache the authorities at the frontend. (LocalStorage / Cookies)
3. Provide an API to verify the access requests.

Some features that *casbin.js* NOT responsible for:
1. Provide any APIs for updating the policies. ( If a user wants to update some authorities from the frontend, he should implement the feature manually. )
2. Storage and management for roles, matchers, policies.

I believe to distinguish the functionalities between *node-casbin* and *casbin.js* is crucial. We can have a brainstorm and dive into details about the target features and functionalities of *casbin.js* at the sync meeting later. 

View my [proposal](https://storage.googleapis.com/summerofcode-prod.appspot.com/gsoc/core_project/doc/4821703194050560_1585573419_Extend_Casbin_to_the_Frontend.pdf?Expires=1591613875&GoogleAccessId=summerofcode-prod%40appspot.gserviceaccount.com&Signature=NqEdB493GtjBCUx5LC%2FC1%2BMjCV7kbJ35yx0EJjhKEqVMhZe%2BbvKUddNe4DPf72cyhLeWLnUJzKa5quM%2FCKA68PRjzHkH3LKkGyctCw1jWUNzYW3hpxS0rboMJ6s48MQEqvbVKNI3an1g6sblCgrXlAWOwaezLocpRVs%2BEKqNyD8E9u3AbTiO8sdR4kYgDMP1qhPs9c9%2FpdVGR4B1sncPQzXVvwnOSGU5ayfyk03%2BkPE1JXISbL%2BDnEfP3BEjZZhJhpsdcf9YJ4omkOjjNPo945ygoJP9vUT982t38%2F5NE09zOVMSnWt3C%2BN2gYXLAq5MJdGBwDANdth1CeMgKqGHCQ%3D%3D) for further details.


## Next week
1. Build up the necessary environment.
2. Finish "Syncing authorities" part.

**Comment by kingiw** [comment]
# Week2 (June 8 - June 14)

## Weekly Summary
1. Set up the basic environment. This included (a) Jest unit test environment for both package methods and server rest api. (b) Code linter. I use eslint and prettier to help format the codes.
2. Syncing the profiles between the frontend and the backend. The following part will illustrate it.

## Syncing the Profiles

### Profiles Definition
Before going further, I wish to introduce a new concept named *profiles* to illustrate my design for Casbin.js. *Profiles* is a bunch of data describing what authorities a given user has. Take the following RBAC model as an example:


```
# rbac_model.conf
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act
```

```csv
# rbac_policy.csv
p, alice, data1, read
p, bob, data2, write
p, data2_admin, data2, read
p, data2_admin, data2, write
g, alice, data2_admin
```
With the model definition and the policies above, we can summarize the authorities of Alice to be:
1. Can read `data1`.
2. Can read and write `data2`, because she is a member of group `data2_admin`.

Here, I use (and will use in the following development) the term *Alice's profiles* to describe the authorities information.

### Profiles Data Structure
To achieve profiles' transmission between the fronend and the backend and the storage at frontend, profiles should be serializable. In my picture, profiles can be represented as a JSON object, whose keys are the actions and the values are an array of applicable objects. For instance, Alice profiles can be represented as:
```JSON
{
    "read": ["data1", "data2"],
    "write": ["data2"]
}
```

Another solution is to use protobuf to serialize and deserialize the profiles structures. However, this method may be unnecessarily complicated.


### Profiles Generation
Temporarily I used a RBAC model as an example to implement my idea.

```javascript
// Input: the subject/user
// Output: the stringified profiles of the subjects/user
public async getProfiles(sub: string) : Promise<string> {

    // Call the existed RBAC model API to fetch the policies
    const policies = await this.enforcer.getImplicitPermissionsForUser(sub);

    // Construct the profiles
    let profiles : { [key:string]: string[] } = {};
    policies.forEach(policy => {
        if (!profiles.hasOwnProperty(policy[2])) {
            profiles[policy[2]] = [];
        }
        profiles[policy[2]].push(policy[1]);
    })
    return JSON.stringify(profiles);
}
```

### Fetching the profiles
In my picture, the frontend page can raise asynchronous request to fetch the profiles of a specified user. A simple implementation is to let the developer come up with an restful api, which requires a parameters indicating the user that the frontend wish to know about, like:
```Javascript
// Set a router at an Express server
this.app.get('/api/casbin', async (req: express.Request, res: express.Response) => {
    // Get the subject/user
    const sub = String(req.query["casbin_subject"]);
    const profiles = await this.casbinServ.getProfiles(sub);
    res.status(200).json({
        message: 'ok',
        data: profiles
    })
})
```
Then the frontend can raise request toward `[domain]/api/casbin` with the parameter `casbin_subject=[subject/user]`.

## Next week
1. Go on with the implementation of "syncing the profiles", including frontend storage and cookies supports.
2. Implement some enforcement api for Casbin.js (like `enforce`).

**Comment by kingiw** [comment]
# Week 3 & 4 (June 15 - June 28)
## Weekly Summary
1. Implement class `Profiles` that provides interfaces for creating and manipulating user profiles in different ways.
2. Redesign and implement some of the enforcer's interfaces.
3. Scripts bundling. 

Casbin.js will be used as an npm package. Maybe we need to upload our library codes to the npm community? 

I believe Casbin.js will also be used as a bundled javascript project in the browser via referring JS scripts in `<script>`. Maybe we need to use some CDN server to maintain our project. [jsdelivr](https://www.jsdelivr.com/) can be a choice.

## Next Week
1. Implement the "Controller", which manipulates the visibility of the UI widgets.
2. Unit test in headless browser.
3. More interfaces and other details for the `Profiles` and `Enforcer`.

**Comment by kingiw** [comment]
# Week 5 - 7 (June 30 - July 19)

Sorry for the absence of my weekly reports.

Now Casbin.js is available on npm and jsdelivr cdn!

### Weekly Summary

Design 3 modes for Casbin.js:
1. `auto`, where users specified an endpoint of a backend Casbin service (normally a pre-defined RESTFul API). Casbin.js will automatically fetch the permission when the identity of the frontend visitors changes.
2. `manual`, where users can specify the permissions as they want via the API `setPermission`.
3.  `cookie`, where Casbin.js will load the cookie and retrieve the permission information.

Mode `auto` and `manual` are released and documented in README. As for `cookie` mode, I believe we need to have some further discussion about the details. Maybe we can ask for our customers opinions.

I also finished the following part during the last 3 weeks:
1. Create a React demo to illustrate the usage of Casbin.js.
2. Add `casbin-server-integration`, which facilitates our users to generate permissions info, for node-casbin and go casbin.

What I am currently doing:
1. Add a module name *CSS Controller*. However, I am suspected about my design because it seems useless to equip Casbin.js in an extremely native HTML webpage. [details](https://github.com/kingiw/casbin.js/tree/cssctl/extensions/casbin-js-css-controller)
2.  Integrate with other modern frontend framework. I try to create a Casbin.js component as part of our extension to React, but it seems unnecessary because the design will harmfully restrict the availability of Casbin.js in React. You can see how we integrate Casbin.js with React App [here](https://github.com/kingiw/casbin.js/blob/master/example/react/src/CasbinDemo.js). As for further development, I think we need a detailed discussion over that.
3. Add Casbin.js introduction to our Casbin official webpage.
4. As Yang mentioned in our IM group, `gin-vue-admin` may be our potential customers. See [here](https://github.com/flipped-aurora/gin-vue-admin/issues/141). I am willing to get involved in it.

## Next week
I will finish the docs first before going further in the feature enhancement over modern frontend frameworks.

**Comment by hsluoyz** [comment]
Closed as completed.
